# Generated by Django 5.2 on 2025-04-17 16:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пост из Telegram',
                'verbose_name_plural': 'Посты из Telegram',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='telegram_po_publish_03f99e_idx')],
            },
        ),
    ]
