# Generated by Django 5.2 on 2025-04-17 16:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('lang', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2)),
                ('is_draft', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['lang'], name='news_news_lang_92103a_idx'), models.Index(fields=['is_draft'], name='news_news_is_draf_f07fae_idx'), models.Index(fields=['published_at'], name='news_news_publish_377f0e_idx'), models.Index(fields=['slug'], name='news_news_slug_915ecd_idx')],
            },
        ),
    ]
