# Generated by Django 5.2 on 2025-04-17 16:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('image', models.ImageField(upload_to='podcasts/images/')),
                ('is_draft', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2)),
            ],
            options={
                'verbose_name': 'Подкаст',
                'verbose_name_plural': 'Подкасты',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['lang'], name='podcasts_po_lang_2cbfc4_idx'), models.Index(fields=['is_draft'], name='podcasts_po_is_draf_f99979_idx'), models.Index(fields=['published_at'], name='podcasts_po_publish_99effa_idx')],
            },
        ),
    ]
