# Generated by Django 5.2 on 2025-04-17 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['lang', 'key'],
                'indexes': [models.Index(fields=['lang'], name='localizatio_lang_af074e_idx'), models.Index(fields=['key'], name='localizatio_key_17a5ad_idx')],
                'unique_together': {('lang', 'key')},
            },
        ),
    ]
