# Generated by Django 5.2 on 2025-04-17 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('languages', models.JSONField(default=list)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lawyers/photos/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адвокат',
                'verbose_name_plural': 'Адвокаты',
                'ordering': ['-experience_years'],
                'indexes': [models.Index(fields=['specialization'], name='lawyers_law_special_71d98d_idx'), models.Index(fields=['experience_years'], name='lawyers_law_experie_5a2b2a_idx'), models.Index(fields=['is_featured'], name='lawyers_law_is_feat_c3ef3f_idx')],
            },
        ),
    ]
