# Generated by Django 5.2 on 2025-05-05 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('content_encrypted', models.TextField(verbose_name='Зашифрованное содержимое')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='Зашифровано')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_deleted_by_sender', models.BooleanField(default=False, verbose_name='Удалено отправителем')),
                ('is_deleted_by_recipient', models.BooleanField(default=False, verbose_name='Удалено получателем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
