# Generated by Django 5.2 on 2025-05-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_pgpkey_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGPKey',
        ),
    ]
