# Generated by Django 5.2 on 2025-05-06 08:33

import mail.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_delete_pgpkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=mail.models.get_attachment_file_path, verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байт)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип содержимого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='attachments_meta',
            field=models.JSONField(blank=True, default=list, verbose_name='Метаданные вложений'),
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='attachments',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='messages', to='mail.mailattachment', verbose_name='Вложения'),
        ),
    ]
