# Generated by Django 5.2 on 2025-05-06 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_mailattachment_mailmessage_attachments_meta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGPKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField(verbose_name='Публичный ключ')),
                ('private_key_encrypted', models.TextField(verbose_name='Зашифрованный приватный ключ (AES-256)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pgp_key', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'PGP ключ',
                'verbose_name_plural': 'PGP ключи',
                'ordering': ['-created_at'],
            },
        ),
    ]
