# Generated by Django 5.2 on 2025-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_pgpkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='private_key_encrypted',
            field=models.TextField(verbose_name='Зашифрованный приватный ключ'),
        ),
    ]
