# Generated by Django 5.2 on 2025-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_pgpkey_updated_at_alter_pgpkey_private_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='session_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия ключа сессии'),
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ сессии (AES-256)'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='private_key_encrypted',
            field=models.TextField(verbose_name='Зашифрованный приватный ключ (AES-256)'),
        ),
    ]
