# Generated by Django 5.2 on 2025-05-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_pgpkey_session_expires_pgpkey_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgpkey',
            name='session_expires',
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='session_key_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия сессионного ключа'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='session_key',
            field=models.TextField(blank=True, null=True, verbose_name='Сессионный ключ (AES-256)'),
        ),
    ]
