# Generated by Django 5.2 on 2025-05-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_remove_pgpkey_session_expires_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgpkey',
            options={'verbose_name': 'PGP ключ', 'verbose_name_plural': 'PGP ключи'},
        ),
        migrations.RemoveField(
            model_name='pgpkey',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='pgpkey',
            name='session_key_expires',
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='private_key_encrypted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pgp_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
