# Generated by Django 5.2 on 2025-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_alter_pgpkey_options_remove_pgpkey_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='session_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
