# Generated by Django 5.2 on 2025-05-08 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_pgpkey_session_expires_pgpkey_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgpkey',
            options={'ordering': ['-created_at'], 'verbose_name': 'PGP ключ', 'verbose_name_plural': 'PGP ключи'},
        ),
        migrations.RemoveField(
            model_name='pgpkey',
            name='password',
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='private_key_encrypted',
            field=models.TextField(verbose_name='Зашифрованный приватный ключ (AES-256)'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='public_key',
            field=models.TextField(verbose_name='Публичный ключ'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='session_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия ключа сессии'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ сессии (AES-256)'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pgp_key', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
